### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by javiavid** [GambitEngine/obsidian-transcription#1]
I have whisper installed on the system (windows) to use it in subtitle edit or cmd and it works fine, but when I use your plugin nothing happens.

What model do you use for the transcription (small.en, medium...)?

**Comment by djmango** [comment]
Currently the backend calls to [Whisper ASR](https://github.com/ahmetoner/whisper-asr-webservice) which you can run via docker or natively. I've started working on a host of other backends that you can choose from, including the local install of whisper, looking at how [Obsidian OCR](https://github.com/MohrJonas/obsidian-ocr/) by Jonas Mohr implements the same with OCR.

I'll make the model size configurable in the settings when local whisper transcription is implemented.

**Comment by javiavid** [comment]
Thanks

**Comment by abdcef** [comment]
Hi, thanks for the plugin. Can you add an indicator to show if the transcription is running or not?

**Comment by djmango** [comment]
> 

Sure, could you create a new Issue for that with some details as to how to expect it to look and function?

**Comment by djmango** [comment]
Latest dev build now works on any device, including mobile, without installing third party tools - contact me via email or sign up at https://scribe.gambitengine.com for early access!
