### ISSUE TITLE
Add support for WhisperCPP

### ISSUE THREAD

**Issue by MartinBernstorff** [GambitEngine/obsidian-transcription#7]
Awesome plugin! Haven't had much of a look in the architecture, but support for the [C++](https://github.com/ggerganov/whisper.cpp) implementation locally would be super powerful!

**Comment by djmango** [comment]
Thanks! I've begun working on a `TranscriptionEngine` prototype to allow all sorts of backends, and did a bit of preliminary digging, CLI-based transcription engines are definitely doable.

My main concern is that I want to keep this plugin accessible on mobile, and I'm not sure the best way (or if it's even possible) to fence off sections of the plugin like CLI-based engines from mobile to keep that compatibility.

Any thoughts?
