### ISSUE TITLE
Custom timestamp format

### ISSUE THREAD

**Issue by dxcore35** [GambitEngine/obsidian-transcription#8]
Hello! 

I'm using your plugin with the Audio plugin:
https://github.com/noonesimg/obsidian-audio-player

And they complement each other amazingly! The only problem is that the transcription from AI model are using diffrent timestamp format than the audio-player plugin is using. It will be beneficial for all kind of other plugin if user can specify the timestamp format.

For example the obsidian-audio-player needs format:

```audio-player
[[my awesome audio file.mp3]]
00:00:44 --- chapter
00:01:50 --- chapter 2 
00:02:40 --- chapter 3 in which nothing happened
```

**Comment by djmango** [comment]
Added in the latest [dev build](https://github.com/GambitEngine/obsidian-transcription/actions/runs/4169167818) - also now works on any device, - contact me at sulaiman@gambitengine.com or sign up at https://scribe.gambitengine.com/ for early access!

<img width="543" alt="image" src="https://user-images.githubusercontent.com/28496988/218607217-4eda2bf6-8448-48ef-8dd0-d4862a1e14e0.png">
